services:
  # A name for your service on Render
  - name: knowledge-assistant-app
    # The type of service to create
    type: web
    # Tell Render to build and run this service from a Dockerfile
    env: docker
    
    # Enable auto-deploys from the main branch of your repo
    autoDeploy: true
    branch: main # Or whichever branch you use for production

    # Health check to ensure zero-downtime deploys
    # Render will wait for this to return a 200 OK before switching traffic.
    healthCheck:
      path: /
      # Give the app plenty of time to load models on first start
      initialDelaySeconds: 180

    # Define a persistent disk to store your SQLite databases and sync state.
    # This ensures your data is not lost when the service restarts or redeploys.
    disks:
      - name: app-data
        # This mount path must match the WORKDIR in your Dockerfile + the directory name
        mountPath: /usr/src/app/database
        sizeGB: 1