services:
  # Main web service for the application
  - name: knowledge-assistant-app
    type: web
    env: docker
    plan: free
    autoDeploy: true
    branch: main
    healthCheck:
      path: /
      initialDelaySeconds: 180
    disks:
      - name: app-data
        mountPath: /usr/src/app/database
        sizeGB: 1

  # Cron job service to synchronize documents
  - name: document-synchronizer
    type: cron
    plan: free
    schedule: "*/15 * * * *"
    # The command is wrapped in single quotes to avoid YAML parsing issues
    command: 'curl -fs -X POST -H "X-Sync-Token: ${SYNC_SECRET_TOKEN}" https://${RENDER_EXTERNAL_URL}/admin/sync_documents'