services:
  # Main web service for the application
  - name: knowledge-assistant-app
    type: web
    env: docker
    plan: free
    autoDeploy: true
    branch: main
    healthCheck:
      path: /
      initialDelaySeconds: 90
    # The 'disks:' section is GONE.

  # Cron job service to synchronize documents
  - name: document-synchronizer
    type: cron
    plan: free
    schedule: "0 0 * * *"
    command: 'curl -fs -X POST -H "X-Sync-Token: ${SYNC_SECRET_TOKEN}" https://${RENDER_EXTERNAL_URL}/admin/sync_documents'
    envVars:
      - key: SYNC_SECRET_TOKEN
        fromService:
          type: web
          name: knowledge-assistant-app
          envVarKey: SYNC_SECRET_TOKEN